--
-- PostgreSQL database dump
--

\restrict Pb7GawaGjVS4i8yhdO5W2448HfOy41lQvwn4IKZi6icnzRymGzDBiWJO5baCRG9

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: allergen; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.allergen (
    id integer NOT NULL,
    label character varying(255) NOT NULL
);


--
-- Name: allergen_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.allergen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.allergen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diet (
    id integer NOT NULL,
    label character varying(255) NOT NULL
);


--
-- Name: diet_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.diet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dish; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dish (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    photo bytea NOT NULL
);


--
-- Name: dish_allergen; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dish_allergen (
    dish_id integer NOT NULL,
    allergen_id integer NOT NULL
);


--
-- Name: dish_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dish ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


--
-- Name: menu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    min_people_amount integer NOT NULL,
    price_per_people numeric(10,2) NOT NULL,
    remaining integer NOT NULL,
    theme_id integer NOT NULL,
    diet_id integer NOT NULL
);


--
-- Name: menu_dish; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_dish (
    menu_id integer NOT NULL,
    dish_id integer NOT NULL
);


--
-- Name: menu_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: opening_hours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.opening_hours (
    id integer NOT NULL,
    day character varying(20) NOT NULL,
    open_time time(0) without time zone DEFAULT NULL::time without time zone,
    close_time time(0) without time zone DEFAULT NULL::time without time zone
);


--
-- Name: opening_hours_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.opening_hours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.opening_hours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."order" (
    id integer NOT NULL,
    order_number character varying(255) NOT NULL,
    order_date timestamp(0) without time zone NOT NULL,
    date_prestation date NOT NULL,
    delivery_hour time(0) without time zone NOT NULL,
    menu_price numeric(10,2) NOT NULL,
    delivery_price numeric(10,2) NOT NULL,
    people_amount integer NOT NULL,
    status character varying(255) NOT NULL,
    equipment_lent boolean NOT NULL,
    equipment_return boolean NOT NULL,
    user_id integer NOT NULL,
    menu_id integer NOT NULL,
    address character varying(255) DEFAULT NULL::character varying,
    city character varying(255) DEFAULT NULL::character varying,
    zip_code character varying(255) DEFAULT NULL::character varying,
    country character varying(255) DEFAULT NULL::character varying
);


--
-- Name: order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."order" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review (
    id integer NOT NULL,
    status character varying(255) NOT NULL,
    note integer NOT NULL,
    text text,
    user_id integer NOT NULL,
    order_id integer
);


--
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: theme; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.theme (
    id integer NOT NULL,
    label character varying(255) NOT NULL
);


--
-- Name: theme_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.theme ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.theme_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    email character varying(180) NOT NULL,
    roles json NOT NULL,
    password character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    country character varying(255) DEFAULT NULL::character varying,
    city character varying(255) DEFAULT NULL::character varying,
    zip_code character varying(255) DEFAULT NULL::character varying,
    adress character varying(255) DEFAULT NULL::character varying,
    enabled boolean NOT NULL
);


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: allergen allergen_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allergen
    ADD CONSTRAINT allergen_pkey PRIMARY KEY (id);


--
-- Name: diet diet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diet
    ADD CONSTRAINT diet_pkey PRIMARY KEY (id);


--
-- Name: dish_allergen dish_allergen_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dish_allergen
    ADD CONSTRAINT dish_allergen_pkey PRIMARY KEY (dish_id, allergen_id);


--
-- Name: dish dish_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dish
    ADD CONSTRAINT dish_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: menu_dish menu_dish_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_dish
    ADD CONSTRAINT menu_dish_pkey PRIMARY KEY (menu_id, dish_id);


--
-- Name: menu menu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT menu_pkey PRIMARY KEY (id);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: opening_hours opening_hours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.opening_hours
    ADD CONSTRAINT opening_hours_pkey PRIMARY KEY (id);


--
-- Name: order order_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_pkey PRIMARY KEY (id);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- Name: theme theme_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.theme
    ADD CONSTRAINT theme_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: idx_3c4389a5148eb0cb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_3c4389a5148eb0cb ON public.dish_allergen USING btree (dish_id);


--
-- Name: idx_3c4389a56e775a4a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_3c4389a56e775a4a ON public.dish_allergen USING btree (allergen_id);


--
-- Name: idx_5d327cf6148eb0cb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_5d327cf6148eb0cb ON public.menu_dish USING btree (dish_id);


--
-- Name: idx_5d327cf6ccd7e912; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_5d327cf6ccd7e912 ON public.menu_dish USING btree (menu_id);


--
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- Name: idx_794381c68d9f6d38; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_794381c68d9f6d38 ON public.review USING btree (order_id);


--
-- Name: idx_794381c6a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_794381c6a76ed395 ON public.review USING btree (user_id);


--
-- Name: idx_7d053a9359027487; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_7d053a9359027487 ON public.menu USING btree (theme_id);


--
-- Name: idx_7d053a93e1e13ace; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_7d053a93e1e13ace ON public.menu USING btree (diet_id);


--
-- Name: idx_f5299398a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_f5299398a76ed395 ON public."order" USING btree (user_id);


--
-- Name: idx_f5299398ccd7e912; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_f5299398ccd7e912 ON public."order" USING btree (menu_id);


--
-- Name: uniq_identifier_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_identifier_email ON public."user" USING btree (email);


--
-- Name: dish_allergen fk_3c4389a5148eb0cb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dish_allergen
    ADD CONSTRAINT fk_3c4389a5148eb0cb FOREIGN KEY (dish_id) REFERENCES public.dish(id) ON DELETE CASCADE;


--
-- Name: dish_allergen fk_3c4389a56e775a4a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dish_allergen
    ADD CONSTRAINT fk_3c4389a56e775a4a FOREIGN KEY (allergen_id) REFERENCES public.allergen(id) ON DELETE CASCADE;


--
-- Name: menu_dish fk_5d327cf6148eb0cb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_dish
    ADD CONSTRAINT fk_5d327cf6148eb0cb FOREIGN KEY (dish_id) REFERENCES public.dish(id) ON DELETE CASCADE;


--
-- Name: menu_dish fk_5d327cf6ccd7e912; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_dish
    ADD CONSTRAINT fk_5d327cf6ccd7e912 FOREIGN KEY (menu_id) REFERENCES public.menu(id) ON DELETE CASCADE;


--
-- Name: review fk_794381c68d9f6d38; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk_794381c68d9f6d38 FOREIGN KEY (order_id) REFERENCES public."order"(id);


--
-- Name: review fk_794381c6a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk_794381c6a76ed395 FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: menu fk_7d053a9359027487; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT fk_7d053a9359027487 FOREIGN KEY (theme_id) REFERENCES public.theme(id);


--
-- Name: menu fk_7d053a93e1e13ace; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT fk_7d053a93e1e13ace FOREIGN KEY (diet_id) REFERENCES public.diet(id);


--
-- Name: order fk_f5299398a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_f5299398a76ed395 FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: order fk_f5299398ccd7e912; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_f5299398ccd7e912 FOREIGN KEY (menu_id) REFERENCES public.menu(id);


--
-- PostgreSQL database dump complete
--

\unrestrict Pb7GawaGjVS4i8yhdO5W2448HfOy41lQvwn4IKZi6icnzRymGzDBiWJO5baCRG9

